@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' Контекст-Система
Person(user, "Пользователь", "")
System_Boundary(cinema, "CinemaAbyss") {
  System(apiGateway, "API Gateway", "Единая точка входа для пользователя (HTTP)")
  ContainerDb(db, "PostgreSQL", "Database", "Хранит всю информацию: users, movies, payments, subscriptions")
  Container(userService, "User Service", "Microservice", "Управление пользователями")
  Container(movieService, "Movie Service", "Microservice", "Управление фильмами")
  Container(paymentService, "Payment Service", "Microservice", "Оплата")
  Container(subscriptionService, "Subscription Service", "Microservice", "Управление подписками")

  Container(kafka, "Kafka Broker", "Message broker", "Доставка событий рекомендаций")
  Container(recommendationService, "Recommendation Service", "Microservice", "Отвечает за предоставление рекомендаций пользователю")
}
Rel(user, apiGateway, "", "HTTPS")

' Связи контейнеров
Rel(apiGateway, userService, "REST/JSON", "CRUD")
Rel(apiGateway, movieService, "REST/JSON", "CRUD & поиск")
Rel(apiGateway, paymentService, "REST/JSON", "Оплата")
Rel(apiGateway, subscriptionService, "REST/JSON", "CRUD")
Rel(apiGateway, recommendationService, "REST/JSON", "Получение рекомендаций")

' Хранение данных
Rel(userService, db, "SQL", "Users")
Rel(movieService, db, "SQL", "Movies")
Rel(paymentService, db, "SQL", "Payments")
Rel(subscriptionService, db, "SQL", "Subscriptions")

' Рекомендации в Kafka
Rel(movieService, kafka, "Publish", "Просмотренные фильмы")
Rel(kafka, recommendationService, "Consume", "Расчитанные рекомендации")
Rel(recommendationService, userService, "Read", "Предпочтения пользователей")
Rel(recommendationService, db, "Read/Write", "Кэш рекомендаций")

' apiGateway
Rel(user, apiGateway, "HTTPS", "Запросы")

@enduml